query FilteredListings(
  $endDate: DateTime
  $limit: Int
  $location: String
  $maxPrice: Float
  $minPrice: Float
  $page: Int
  $search: String
  $sort_col: String
  $sort_dir: String
  $startDate: DateTime
  $status: Int
) {
  data: filteredListings(
    endDate: $endDate
    limit: $limit
    location: $location
    maxPrice: $maxPrice
    minPrice: $minPrice
    page: $page
    search: $search
    sort_col: $sort_col
    sort_dir: $sort_dir
    startDate: $startDate
    status: $status
  ) {
    limit
    nodes {
      id
      title
      description
      pricePerNight
      location
      availableFrom
      availableTo
      status
      host {
        id
      }
      bookings {
        id
      }
      reviews {
        id
      }
      images {
        id
        url
      }
      category {
        id
      }
      createdAt
      updatedAt
    }
    other_count
    page
    total_count
  }
}


query FindOneListing($id: String!) {
  data: findOneListing(id: $id) {
    availableFrom
    availableTo
    bookings {
      checkInDate
      checkOutDate
      createdAt
      guestId
      id
      listingId
      paymentId
      totalPrice
      updatedAt
    }
    category {
      createdAt
      id
      name
      updatedAt
    }
    categoryId
    createdAt
    description
    host {
      bio
      createdAt
      email
      id
      name
      phone
      role
      updatedAt
      usercode
    }
    hostId
    id
    images {
      createdAt
      id
      listingId
      name
      updatedAt
      url
    }
    location
    pricePerNight
    reviews {
      comment
      createdAt
      id
      listingId
      rating
      reviewerId
      updatedAt
    }
    status
    title
    updatedAt
  }
}